---
title: "Factor Analysis on Music Dataset"
author: "Laurine KOMENDANCZYK"
date: "2022-09-29"
output: html_document
---

### Dataset importation
```{r}
library(data.table)
music <- fread("Shiny/Data/musique.csv", sep=";", dec=".")

#as.factor
music$artist_name = as.factor(music$artist_name)
music$track_name = as.factor(music$track_name)
music$instance_id = as.factor(music$instance_id)
music$mode = as.factor(music$mode)
music$obtained_date = as.factor(music$obtained_date)
music$music_genre = as.factor(music$music_genre)
music$key = as.factor(music$key)

#as.numeric
music$acousticness = as.numeric(music$acousticness)
music$instrumentalness = as.numeric(music$instrumentalness)
music$tempo=as.numeric(music$tempo)

## CLEANING 

music <- na.omit(music) # drop rows with NAs
music <- music[which(music$duration_ms>0)] # keep rows with positive durations_ms
music <- music[which(artist_name!="empty_field")] # remove rows 
music <- droplevels(music) # droplevels 


# vérif que l'id est bien unique
music[,list(nbr =.N),by=instance_id][which(nbr>1)]

# remove duplicated lines with different popularity grades 
# we choose to keep the highest popularity grade

library(dplyr)
options(dplyr.summarise.inform = FALSE)
music <- music %>% dplyr::group_by(artist_name,track_name) %>%
  dplyr::summarise(instance_id = instance_id[which.max(popularity)],popularity = max(popularity)) %>% 
  dplyr::inner_join(music, music2, by = "instance_id", copy=FALSE, suffix = c("","."))


music <- as.data.frame(music)
musique <- music[,-(5:7)]
summary(musique)
```

### Nettoyage du jeu de données
```{r}

# summary(musi)

# instance_id = which.max(popularity),

# musiques en double ? 
music[,list(nbr =.N), by=list(artist_name, track_name)][which(nbr>1)]
anyDuplicated(musique)

music2 <- music[,list(new_id = instance_id,popularity_mean = mean(popularity)),by=list(artist_name,track_name) ]
music2[,new_id]
music2[,list(nbr =.N, new_id, popularity_mean), by=list(artist_name, track_name)][which(nbr>1)]

music2[which(music2$artist_name.1!=music2$artist_name.2)]

```
il semble que des combinaisons (artist_name, track_name) soit en double ou en triple. dû au fait qu'un titre sort parfois en single et en album.s
on choisit donc pour ces titres de ne garder qu'une ligne où la popularité est la moyenne des popularités pour cette chanson 


```{r}
summary(music)
```



### AFDM
```{r}
library(FactoMineR)
library(Factoshiny)

dim(musique)
summary(musique)

res.FAMD <- FAMD(musique[,-c(1:3,16)], 
                 ncp = 4, 
                 graph = TRUE, 
                 sup.var = c("danceability", "energy", "popularity", "valence", "music_genre")
                 )

names(res.FAMD)
summary(music$key)

Factoshiny(res.FAMD)

x <- res.FAMD$quanti.var$coord[,"Dim.1"]
y <- res.FAMD$quanti.var$coord[,"Dim.2"]
plot(y~x)
```

### FAMD sur échantillon du dataset 

```{r}
library(dplyr)
# summary(musique$music_genre)


# Subset: 10% of each music_genre 
subset <- musique %>% 
  group_by(music_genre) %>%
  sample_frac(size = 0.10, replace = FALSE)

# dim(subset)


#FAMD on subset
res.FAMD <- FAMD(subset[,-c(1:3,16)], 
                 ncp = 4, 
                 graph = FALSE, 
                 sup.var = c("danceability", "energy", "popularity", "valence", "music_genre")
                 )

Factoshiny(res.subset)

# Graphe indiv modalités 
# plot.FAMD(res.FAMD,invisible=c('quali','ind.sup'),habillage=14,title="Graphe des individus et des modalités",cex=0.85,cex.main=0.85,cex.axis=0.85)
plot.FAMD(res.FAMD,invisible=c('quali','quali.sup','ind.sup'),select = 'all' ,habillage=7,title="Graphe des individus et des modalités",cex=0.85,cex.main=0.85,cex.axis=0.85)


# Features graph 
plot.FAMD(res.FAMD,axes=c(1,2),choix='var',cex=1.15,cex.main=1.15,cex.axis=1.15,title="Graphe des variables")


# Correlation circle 
plot.FAMD(res.FAMD, choix='quanti',title="Cercle des corrélations")

```




```{r}
class(match("key", colnames(subset[,-c(1:3,16)])))


```

